apiVersion: v1
kind: Pod
metadata:
  name: two
spec:

  restartPolicy: Never

  volumes:
  - name: shared-data
    emptyDir: {}

  containers:

  - name: nginx-contain
    image: nginx
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
    ports:
    - containerPort: 80
  - name: side
    image: busybox:1.28
    args: [/bin/sh, -c, 'while true; do echo $(date); sleep 1; done']
